sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker
before_install: 
    - docker build -t byronliuls/sample-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true byronliuls/sample-app npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2" ### AWS region of your choice
  app: "sample-docke-react" ### Your EB App name
  env: "Sampledockereact-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-ap-southeast-2-785090856637" ### S3 bucket name
  bucket_path: "EBApptest" ### S3 folder name under S3 bucket above
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
